### ISSUE TITLE
no header file CommandRobotiqGripperAction.h 

### ISSUE THREAD

**Issue by tunguyenmta** [Danfoa/robotiq_2finger_grippers#1]
I follow all your installation but when I build the package I receive fatal error  fatal error: robotiq_2f_gripper_msgs/CommandRobotiqGripperAction.h: No such file or directory
I check all package and I find that no file like that in the package 
So pls help me to update the file 
I want to ask a question about create cartesian trajectory I have create a custom arm with 3 Dof and then I can simulate it on gazebo and Rviz I can use the random valid for arm and execute it on Rviz and Gazebo but when I try coding to send command to Moveit to plan a trajectory there are no valid sample and no plan found (I also check the end effector from tflistener to get ee pose ) so I am sure that the pose is valid I using Trac-Ik for arm

**Comment by Danfoa** [comment]
I cannot seem to get the same error at build with catkin tools, please clean your workspace and retry the build, if the problem persists I will have a deeper look at it.
```
cd <path to your workspace>
catkin clean
# or 
rm -r devel 
rm -r build 
catkin build  # or catkin_make
```

Regarding the other inquiry, I am afraid is hard to comprehend what your issue is, but I have to note that this package does not support FollowJointTrajectory action, which is the default group controller used by Moveit! (This is something that I will include soon), meaning that you cannot plan joint trajectories with moveit for the gripper for the moment.

**Comment by tunguyenmta** [comment]
![Screenshot from 2019-03-29 15-54-16](https://user-images.githubusercontent.com/35488611/55244245-67574500-5273-11e9-8cb7-4327352e0c7d.png)
![Screenshot from 2019-03-29 15-57-12](https://user-images.githubusercontent.com/35488611/55244312-8c4bb800-5273-11e9-97be-d405b982f6b3.png)

Thank for your guide I can build it now but when I start the tutorial many error I get with move group  interface. Group torso is not a chain so the KDL_kinematic plugin can't initialize how can we fix it .
And it can't demo like your video on youtube with joint-space and square drawing
I'm really new with ROS Thanks in advance

**Comment by Danfoa** [comment]
@tunguyenmta This issues you mention are not related to this repository but to the ` invite_robotics` one. The KDL errors are "normal" Moveit errors and do not limit the functionality of the simulation or path planning.
